# diagonal square  # diagonal rectagular  
# |3 0 0 1 |       #|3 0 0 0 1 2 3| 
# |0 4 0 0 |       #|3 4 0 0 3 4 5| 
# |1 1 3 0 |       #|3 0 6 0 2 3 4| 
# |1 1 0 4 |        
 
 

# Symmetric Matrix
## is a square matrix  same rows and columns
# | 1 -1  0| 
# |-1 -2 -4| 
# | 0 -4  5| 
### Symmetric 
# mirror numbers 



# identity matrix 
# | 1 0 0 | 
# | 0 1 0 | 
# | 0 0 1 | 
# refer to I

# Diagonal matrix 
# |1 0 0 | 
# |0 2 0 | 
# |0 0 4 | 
# the off diagonal numbers are 0  
# can be square or not 
# Diagonal matrix 
# |1 0 0 0 0|  this is as well a Diagonal 
# |0 2 0 0 0|  Matrix.
# |0 0 4 0 0| 


In [3]:
# identity matrix with numpy :)
import numpy as np
np.eye (6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [6]:
np.zeros ((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.full((5,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [12]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#assigment!
#create 3 matrices: 2x2, 2x2, 3x2
#compute scalar-matrix multiplication 
# add all pairs of matrices 

In [19]:
m_1 = np.full((2,2), 2)
m_2 = np.zeros ((2,2))
m_3 = np.array([[1,2],
                [3,4],
                [5,6]])
m_4 = np.array([[1,2],
                [3,4]])
scalar = 3

result = m_1 * scalar
result_2 = m_2 * scalar
result_3 = m_3 * scalar
print(result)
print(result_2)
print(result_3)
#addition
result_4 = m_1 + m_2
#result_5 = m_1 + m_3 it is not possible to add matrices with different dimensions
#result_6 = m_2 + m_3 same problem 
result_7 = m_1 + m_4
print(result_4)
#print(result_5) error 
#print(result_6) same error
print(result_7)

[[6 6]
 [6 6]]
[[0. 0.]
 [0. 0.]]
[[ 3  6]
 [ 9 12]
 [15 18]]
[[2. 2.]
 [2. 2.]]
[[3 4]
 [5 6]]
